name       : iotop
version    : 0.6
release    : 7
source     :
    - http://guichaz.free.fr/iotop/files/iotop-0.6.tar.gz : 1a7c02fd3758bb048d8af861c5f8735eb3ee9abadeaa787f27b8af2b1eaee8ce
homepage   : http://guichaz.free.fr/iotop/
license    : GPL-2.0
component  : system.utils
summary    : iotop shows I/O activity similar to "top"
description: |
    Linux has always been able to show how much I/O was going on
    (the bi and bo columns of the vmstat 1 command).
    iotop is a Python program with a top like UI used to
    show of behalf of which process is the I/O going on.
builddeps  :
    - pkgconfig(python3)
setup      : |
    %patch -p1 < $pkgfiles/iotop-python3build.patch
    %patch -p1 < $pkgfiles/iotop-0.6-python3.patch
    %patch -p1 < $pkgfiles/iotop-0.3.2-batchprintutf8.patch

    %python3_setup
install    : |
    %python3_install
    chmod 00644 $installdir/usr/share/man/man8/iotop.8
