name        : iotop
version     : 0.5
release     : 3
source      :
    - http://guichaz.free.fr/iotop/files/iotop-0.5.tar.gz : 456af4816915a11d678847a53b05323bb96bda6e68d061af82bdf02b5a544ef5
homepage    : http://guichaz.free.fr/iotop/
license     :
    - GPL-3.0
summary     : iotop shows I/O activity similar to "top"
builddeps   :
    - pkgconfig(python-2.7)
description : |
    iotop shows I/O activitiy similar to "top".
install    : |
    python setup.py install --root=%installroot% --no-compile -O0
